### ISSUE TITLE
DrMario potential trademark infringement.

### ISSUE THREAD

**Issue by GNUtoo** [Uzebox/uzebox#109]
Hi,

In  uzebox/demos/DrMario/ there is a game. I built that game from the e05013c91a77dc32a541f692c82d91250035d66f revision and ran it (in MAME after converting it to mame format).

And in first screen I see after the animation there is:
" Dr. MARIO (TM)" with a logo that looks a lot like the Dr.Mario game from Nintendo[1].

Then under that there is a doctor that looks like Dr Mario and there is even "(c) 1990 Nintendo"[1].

So to me uzebox/demos/DrMario/DrMario.c looks like something written from scratch that is properly licensed but:
(1) what is on the screen looks at least like a trademark violation.
(2) I've no idea from where the files in demos/DrMario/data/ come from (I didn't try to where the code from "f38cac4 replaced trunk with code from beta5 branch" commit came from) but it might also be a good idea to check if demos/DrMario/data/ files were copied or made from scratch.

Assuming that what is in demos/DrMario/data was not copied from Nintendo, the best way to fix that could be to:
(1) Rename the game to something else, like Dr GNU or whatever and maybe remove the pills around the DrMario/Dr GNU.
(2) Remove the doctor logo (and maybe add some other animal instead)
(3) Remove the Nintendo copyrights

We already have a free software game named Secret Maryo Chronicles[1] that had a similar issue, and the issue was that packaging it in distributions put the distributions at risk of trademark infringement. The first versions looked a lot like Mario[3] (it can be seen by scrolling down that page), and the character from the current version looks like the one in the banner in the top of the page, so they modified their software to look different and avoid (potential) legal issues.

Note that I have nothing to do with Nintendo and I don't like the fact that Nintendo make nonfree software, but they also have a history of trying hard to enforce their trademarks and/or copyrights, so it might be safer for everybody to avoid any issues by modifying slightly the software (and renaming it).

References:
---------------
[1]https://en.wikipedia.org/wiki/Dr._Mario
[2]http://www.secretmaryo.org/
[3]http://www.secretmaryo.org/index.php?page=new_97&sid=

**Comment by weber21w** [comment]
This is explicitly a fan tribute with no attempt or even viable option for monetization on the platform.

Thank you, I agree it's always worth considering such possibilities. Personally I believe this falls under fair use clause and we should keep the fan work unmodified.
