### ISSUE TITLE
Download page issues take 2

### ISSUE THREAD

**Issue by danboid** [Uzebox/uzebox#137]
Ooops!

I'm sorry but I had closed the previous Downloads page ticket too soon.

The "Uzebox enclosure version 2" link on the current Downloads page also links to v1.0 of the case.

Also, you have spelled "ensure" (insure) wrong in the comment "Check both Github repos to insure the one you need. "

How about "Check the README in the directory of the enclosures to ensure you are using the correct one."?

"Check both Github repos" doesn't really make sense as they're both in the same repo, just in different dirs.

**Comment by uze6666** [comment]
Fixed the link and made the message clear enough I think. I mean, the link brings them right onto github with a big picture that show which connector to use. I can't make it more fool proof! So hope that's good enough to close the issue.

**Comment by danboid** [comment]
Very nearly,now!

Could you please fix the spelling of readme.md (reame.md) on the Downloads page.

**Comment by uze6666** [comment]
Done.
