### ISSUE TITLE
Add Uzenet module assembly guide PDF to repo

### ISSUE THREAD

**Issue by danboid** [Uzebox/uzebox#138]
I'm sure there was a Uzenet PDF assembly guide but it doesn't seem to have been uploaded to the repo?

It is almost hard to go wrong building it if you have bought the Uzenet module kit so it doesn't seem very worthwhile going to the trouble of rewriting it if @uze6666 doesn't still have a copy.

**Comment by uze6666** [comment]
Can't find an assembly guide for the Uznet module. Perhaps you say the section in the portable assembly guide? 

Any any case, leave this issue open. Next time I assemble one, I'll snap some pics and make the guide.

**Comment by danboid** [comment]
I thought you had sent one to me somehow but I failed to find it so maybe I imagined it?

I'm not sure a guide is required because I don't think anything can be inserted back to front.
