### ISSUE TITLE
Patch for /trunk/tools/uzem/SDEmulator.h

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Uzebox/uzebox#17]
```
memset is defined in string.h as described 
http://man7.org/linux/man-pages/man3/memset.3.html & 
http://msdn.microsoft.com/en-us/library/aa246471%28v=vs.60%29.aspx

Otherwise, the forward declaration of memset should be made within this file.
```

Original issue reported on code.google.com by `losinggeneration` on 12 Sep 2013 at 5:52

Attachments:
* [SDEmulator.h.patch](https://storage.googleapis.com/google-code-attachments/uzebox/issue-17/comment-0/SDEmulator.h.patch)

**Comment by Uzebox** [comment]
Fixed

**Comment by Uzebox** [comment]
Issue fixed.
