### ISSUE TITLE
gconvert needs a Make install rule

### ISSUE THREAD

**Issue by felipesanches** [Uzebox/uzebox#21]

**Comment by Uzebox** [comment]
Why is that? Only gconvert?

**Comment by felipesanches** [comment]
well... we need an install rule for the tools, not only gconvert.

**Comment by nicksen782** [comment]
Do you mean a Makefile that would compile all the tools in the tools directory instead of individual compiles?

**Comment by felipesanches** [comment]
**install**

**Comment by felipesanches** [comment]
it's been more than 3 years... I would have to look carefully to remember what I originally meant.

But I said "Make install", so it seems the issue was with installing, not compiling.

**Comment by weber21w** [comment]
All tools seem to build in the current codebase? Shall we close?

**Comment by artcfox** [comment]
I think the OP might have meant if you go to the gconvert directory and type make, it will make it in its source directory, rather than make it in the bin/ directory. The solution is to make it from the very top level directory. I think it's safe to close this.
