### ISSUE TITLE
New feature: Possibility to keep duplicate tiles in Gconvert

### ISSUE THREAD

**Issue by Uzebox** [Uzebox/uzebox#24]
It is useful for certain games to keep duplicate tile data (i.e: for vram tricks).

**Comment by nicksen782** [comment]
It appears that this feature exists in Gconvert now. 

Example usage in the XML:  <output file="data/graphics.inc" **_remove-duplicate-tiles="true"_**>

Link to the Gconvert source that accepts this setting: (Line 1118 through 1123.)
https://github.com/Uzebox/uzebox/blob/e09d08eb2f678cecec90f062480c2c36a8e5356a/tools/gconvert/gconvert.cpp#L1118

**Comment by uze6666** [comment]
Yes, this has been there since the very first versions. Closing this issue.
