### ISSUE TITLE
Megatris: options menu misplaces YES/NO string for GhostBlock

### ISSUE THREAD

**Issue by felipesanches** [Uzebox/uzebox#62]
At the options menu, if you press right arrow a few times, you will notice that the "YES" and "NO " strings are misplaced one character position to the right.

Successively pressing left arrow renders the strings in their correct positions.

**Comment by uze6666** [comment]
Strange! I will check it out.

**Comment by Jubatian** [comment]
Confirmed, fixed, tested OK! (sorry for being THIS late :D , didn't notice this yet)
