### ISSUE TITLE
Mode 3 scrolling bug

### ISSUE THREAD

**Issue by weber21w** [Uzebox/uzebox#63]
The issue was discovered and solved by Artcfox, want to make sure we remember to add[ this fix](http://uzebox.org/forums/viewtopic.php?f=3&t=2400) in the next version.

**Comment by artcfox** [comment]
The fix I applied broke mode 3 scrolling with 24 tiles tall (different wrap-around trick) so I reverted it. This bug still stands, we just need to find a better way to fix it, or nix the 24 tile tall scrolling mode. Does anyone use that?

**Comment by weber21w** [comment]
Note that I know of. Would #define be in too many places to make both solutions exist?

**Comment by Jubatian** [comment]
Does the recent Mode 3 blitter boost fix this bug?

**Comment by Jubatian** [comment]
As far as my testing shows, the bug seems to be gone. ( http://uzebox.org/forums/viewtopic.php?f=3&t=9389&start=20#p27206 ). If you can confirm, then this could be closed.

**Comment by uze6666** [comment]
Since we haven't hear anymore about this issue, I'm closing it.
