### ISSUE TITLE
sdspiram demo won't run on latest emulator

### ISSUE THREAD

**Issue by ramonschepers** [Uzebox/uzebox#73]
as stated above, i get the following in the emulator's console and the game stops running (no emulator crash) :

unknown spi command: 0

**Comment by Jubatian** [comment]
Which emulator are you using? In Uzem the SPI RAM is not implemented at all, I get a similar result to what you describe (so the "bug" is in the emulator: that it has no SPI RAM). It should work on the real hardware or the CUzeBox emulator.

**Comment by ramonschepers** [comment]
ah, now i see, i was using the latest uzem from the website's main page download ^^;

**Comment by uze6666** [comment]
Uzem is no more supported and the SPI works fine in CUzebox, so closing this.
