### ISSUE TITLE
ControllerTester doesn't work (in emulators)

### ISSUE THREAD

**Issue by danboid** [Uzebox/uzebox#98]
I have tried running the ControllerTester demo with both cuzebox and uzem under Ubuntu 18.04 but could not get it to register input from the emulated keypad joystick.

I don't suppose this demo only works on real hardware does it? I don't currently have a physical uzebox to do any testing with.

**Comment by Jubatian** [comment]
Had seen this before, never really looked into the why. The Controller Tester works on the real hardware (at least for SNES controllers it does). As of now this seems to be the only known broken application on the emulators (CUzeBox follows the mechanism Uzem used for emulating the controllers, so the problem causing the difference is likely the same in both).

**Comment by danboid** [comment]
Thanks for the explanation.

**Comment by uze6666** [comment]
The tool was meant for the real hardware. Following Jubatian answer, I will closing this issue.
